### PR TITLE
add lp_solve support to docker container

### PR DESCRIPTION
**Pull request by rsereda**
phpphp7-fpm and cli now use lp_solve

### CODE REVIEW

**Comment by hendrikniemann** [comment]
I'm not sure if this should be in our source code. If so, this should be the last solution available.

**Comment by chrisstaudt** [comment]
It could also be hosted somewhere else but source_forge takes older links down at some point and we don't want that let our builds crash.

**Comment by rsereda** [comment]
So. Do you accept this push request or can you propose alternatives haw i can add to this application lp_solve_5.5.2.3 support

**Comment by chrisstaudt** [comment]
@rsereda can you just create a new repository for that code? So it is not included here, and Hendrik is more happy? Thanks!

**Comment by rsereda** [comment]
Hello. As you expect i mve lp_solver source to external repo. All changes play around Dockerfile.

**Comment by hendrikniemann** [comment]
Hmm, maybe now we should think about cherry picking the changes because otherwise the code will still be in the repository which would blow up the file size.
Or to make this easy: We just create a new commit on master and copy paste the changed file?

**Comment by rsereda** [comment]
I simple need this changes at Dockerfile file. Haw you will push code not
principal.

Best regards

Roman Sereda

2016-11-21 17:50 GMT+02:00 Hendrik Niemann notifications@github.com:

**Comment by hendrikniemann** [comment]
Closed in favor of #3.

**Pull request closed without merging**
